[build-system]
requires = [
  "hatchling==1.30.1",
  "hatch-vcs==0.5.0",
]
build-backend = "hatchling.build"

[project]
name = "specsuite"
dynamic = ["version"]
description = "A toolbox for processing data from long-slit spectrographs"
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }

authors = [
  { name = "Autumn Stephens" },
  { name = "Zach Berta-Thompson" },
]

dependencies = [
  "lxml",
  "jax",
  "astropy>=7.0",
  "ipywidgets>=8.0",
  "ipympl",
  "joblib>=1.0",
  "matplotlib>=3.0",
  "numpy>=2.0",
  "pandas>=2.0",
  "requests>=2.0",
  "scipy>=1.0",
  "tqdm>=4.0",
  "chromatic-lightcurves",
]

classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]

[project.optional-dependencies]
dev = [
  "black",
  "flake8",
  "snakemake",
]

docs = [
  "mkdocs",
  "mkdocs-jupyter",
]

[project.urls]
Homepage = "https://www.autumnstephens.net/specsuite/"
Repository = "https://github.com/Autumn10677/specsuite"

[tool.hatch.version]
source = "vcs"
fallback-version = "0.0.0"

[tool.hatch.build.targets.wheel]
packages = ["specsuite"]

[tool.hatch.build.targets.sdist]
include = [
  "specsuite/",
  "README.md",
  "LICENSE",
  "pyproject.toml",
]