name: Deploy MkDocs

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}  # ensures micromamba env is active

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          cache-environment: true
          activate-environment: true

      - name: Install local package
        run: python -m pip install -e .

      - name: Install MKdocs dependencies
        run: |
          python -m pip install \
            mkdocs \
            mkdocs-material \
            mkdocs-jupyter \
            pymdown-extensions

      - name: Deploy docs
        run: mkdocs gh-deploy --force
